name: Continuous Compliance Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * *' # Runs daily at 6 AM UTC

jobs:
  compliance:
    name: Run Compliance Scripts
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1  # Set your desired AWS region here

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r compliance/requirements.txt

      - name: Run check_open_ports.py
        run: python compliance/check_open_ports.py

      - name: Run scan_s3_permissions.py
        run: python compliance/scan_s3_permissions.py

      - name: Run detect_iam_risks.py
        run: python compliance/detect_iam_risks.py
